/**
 * Builds the standalone player from src/engine/player.ts into a
 * TypeScript module that exports the minified JS as a string constant.
 * This avoids needing `fs` at runtime in the Next.js client bundle.
 */
import { buildSync } from "esbuild";
import { writeFileSync } from "fs";
import { join } from "path";

const root = join(import.meta.dir, "..");

// Bundle player.ts into a single minified IIFE
const result = buildSync({
  entryPoints: [join(root, "src/engine/player.ts")],
  bundle: true,
  format: "iife",
  minify: true,
  target: "es2020",
  write: false,
});

const jsCode = result.outputFiles[0].text;

// Write as an importable TS module
const output = `// AUTO-GENERATED by scripts/build-player.ts — do not edit\nexport const PLAYER_JS = ${JSON.stringify(jsCode)};\n`;
writeFileSync(join(root, "src/engine/export/player-bundle.ts"), output);

console.log(`player-bundle.ts written (${jsCode.length} bytes of JS)`);
